package pudu.grammar


/** Classes to specify grammar symbols. */

abstract class Symbol

/** Type T refers to the object to be generated by the parser, e.g. an AST node */
class NonTerminal[+T] extends Symbol

/** It is important to note that values associated with some terminals, like
 *  literals and identifiers, are part of the Token objects generated by the lexer,
 *  and not included in the Terminal class */
case class Terminal[+Token](ordinal: Int) extends Symbol:
  override def toString = s"Terminal: $ordinal"

object Terminal:
  inline def apply[T <: reflect.Enum] = new Terminal[T](enumOrdinal[T])
